# coding: utf-8

"""
    PurplShip Multi-carrier API

    PurplShip is a Multi-carrier Shipping API that simplifies the integration of logistic carrier services  # noqa: E501

    OpenAPI spec version: v1
    Contact: hello@purplship.com
    Generated by: https://github.com/PurplShip/purplship-python-client.git
"""


from __future__ import absolute_import

import unittest

import purplship
from purplship.models.card import Card  # noqa: E501
from purplship.rest import ApiException


class TestCard(unittest.TestCase):
    """Card unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCard(self):
        """Test Card"""
        # FIXME: construct object with mandatory attributes with example values
        # model = purplship.models.card.Card()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
