# coding: utf-8

"""
    Purplship Open Source Multi-carrier Shipping API

     Purplship is an open source multi-carrier shipping API that simplifies the integration of logistic carrier services  The **proxy** endpoints are stateless and forwards calls to carriers web services.   # noqa: E501

    OpenAPI spec version: v1-2020.10.0
    Contact: hello@purplship.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TrackingEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'str',
        'description': 'str',
        'location': 'str',
        'code': 'str',
        'time': 'str',
        'signatory': 'str'
    }

    attribute_map = {
        '_date': 'date',
        'description': 'description',
        'location': 'location',
        'code': 'code',
        'time': 'time',
        'signatory': 'signatory'
    }

    def __init__(self, _date=None, description=None, location=None, code=None, time=None, signatory=None):  # noqa: E501
        """TrackingEvent - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._description = None
        self._location = None
        self._code = None
        self._time = None
        self._signatory = None
        self.discriminator = None
        self._date = _date
        self.description = description
        self.location = location
        if code is not None:
            self.code = code
        if time is not None:
            self.time = time
        if signatory is not None:
            self.signatory = signatory

    @property
    def _date(self):
        """Gets the _date of this TrackingEvent.  # noqa: E501

        The tracking event's date  # noqa: E501

        :return: The _date of this TrackingEvent.  # noqa: E501
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this TrackingEvent.

        The tracking event's date  # noqa: E501

        :param _date: The _date of this TrackingEvent.  # noqa: E501
        :type: str
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def description(self):
        """Gets the description of this TrackingEvent.  # noqa: E501

        The tracking event's description  # noqa: E501

        :return: The description of this TrackingEvent.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TrackingEvent.

        The tracking event's description  # noqa: E501

        :param description: The description of this TrackingEvent.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def location(self):
        """Gets the location of this TrackingEvent.  # noqa: E501

        The tracking event's location  # noqa: E501

        :return: The location of this TrackingEvent.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this TrackingEvent.

        The tracking event's location  # noqa: E501

        :param location: The location of this TrackingEvent.  # noqa: E501
        :type: str
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def code(self):
        """Gets the code of this TrackingEvent.  # noqa: E501

        The tracking event's code  # noqa: E501

        :return: The code of this TrackingEvent.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this TrackingEvent.

        The tracking event's code  # noqa: E501

        :param code: The code of this TrackingEvent.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def time(self):
        """Gets the time of this TrackingEvent.  # noqa: E501

        The tracking event's time  # noqa: E501

        :return: The time of this TrackingEvent.  # noqa: E501
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this TrackingEvent.

        The tracking event's time  # noqa: E501

        :param time: The time of this TrackingEvent.  # noqa: E501
        :type: str
        """

        self._time = time

    @property
    def signatory(self):
        """Gets the signatory of this TrackingEvent.  # noqa: E501

        The tracking signature on delivery  # noqa: E501

        :return: The signatory of this TrackingEvent.  # noqa: E501
        :rtype: str
        """
        return self._signatory

    @signatory.setter
    def signatory(self, signatory):
        """Sets the signatory of this TrackingEvent.

        The tracking signature on delivery  # noqa: E501

        :param signatory: The signatory of this TrackingEvent.  # noqa: E501
        :type: str
        """

        self._signatory = signatory

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackingEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackingEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
