# coding: utf-8

"""
    PurplShip Multi-carrier API

    PurplShip is a Multi-carrier Shipping API that simplifies the integration of logistic carrier services  # noqa: E501

    OpenAPI spec version: v1
    Contact: hello@purplship.com
    Generated by: https://github.com/purplship-api/purplship-codegen.git
"""


from __future__ import absolute_import

import unittest

import purplship
from purplship.models.tracking_details import TrackingDetails  # noqa: E501
from purplship.rest import ApiException


class TestTrackingDetails(unittest.TestCase):
    """TrackingDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackingDetails(self):
        """Test TrackingDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = purplship.models.tracking_details.TrackingDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
