# coding: utf-8

"""
    PurplShip Multi-carrier API

    PurplShip is a Multi-carrier Shipping API that simplifies the integration of logistic carrier services  # noqa: E501

    OpenAPI spec version: v1
    Contact: hello@purplship.com
    Generated by: https://github.com/purplship-api/purplship-codegen.git
"""


from __future__ import absolute_import

import unittest

import purplship
from purplship.api.rates import Rates  # noqa: E501
from purplship.rest import ApiException


class TestRates(unittest.TestCase):
    """Rates unit test stubs"""

    def setUp(self):
        self.api = purplship.api.rates.Rates()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch(self):
        """Test case for fetch

        """
        pass


if __name__ == '__main__':
    unittest.main()
